# Build Apptainer images and push them to the GitHub Container Registry of the
# repository.
#
# Runs automatically on pushes to master if they modify a def file and can also
# be executed manually ("workflow_dispatch" event).
# Images from the master branch are pushed with the "latest" tag, others with
# the name of the branch.
#
name: Apptainer Build & Deploy
on: 
  push:
    branches:
      - master
    paths:
      - "*.def"
      - "Makefile"
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish images (disable to only test the build)"
        type: boolean
        default: false

jobs:
    build:
        name: Build
        runs-on: ubuntu-20.04
        steps:
            - name: Install Apptainer
              run: |
                apptainer_version=1.1.5
                wget https://github.com/apptainer/apptainer/releases/download/v${apptainer_version}/apptainer_${apptainer_version}_amd64.deb
                sudo apt-get install ./apptainer_${apptainer_version}_amd64.deb

            - name: Check out code for the container build
              uses: actions/checkout@v3

            - name: Install treep
              run: |
                python3 -m pip install treep

            - name: Build pam_base.sif
              run: make pam_base.sif

            - name: Build pam_mujoco.sif
              run: make pam_mujoco.sif

            - name: Login and Deploy Container
              if: ${{ github.event_name == 'push' || github.event.inputs.publish == 'true' }}
              run: |
                if [ "${GITHUB_REF_NAME}" = "master" ]
                then
                  tag=latest
                else
                  tag=${GITHUB_REF_NAME}
                fi

                echo "Publish images using tag '${tag}'"

                echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

                apptainer push pam_base.sif oras://ghcr.io/${GITHUB_REPOSITORY}/pam_base:${tag}
                apptainer push pam_mujoco.sif oras://ghcr.io/${GITHUB_REPOSITORY}/pam_mujoco:${tag}
